[package]
name = "piecewise"
version = "0.1.0"
authors = ["Scott Moeller <electronjoe@gmail.com>"]
edition = "2018"

[dependencies]
either = "1.5.2"
intervals-general = "0.1.0"
itertools = "0.8.0"
smallvec = "0.6.9"