[package]
name = "piecewise"
version = "0.1.1"
authors = ["Scott Moeller <electronjoe@gmail.com>"]
edition = "2021"

[dependencies]
either = "1.5.2"
intervals-general = "0.1.0"
itertools = "0.13.0"
smallvec = "1.13.2"
